# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
#  - name: Posts
#    url: '#posts'
#    weight: 20
  - name: Publications
    url: '#publication'
    weight: 20
  - name: Team
    url: '#team'
    weight: 30
  - name: Fieldwork
    url: '#fieldwork'
    weight: 40
  - name: Contact
    url: '#contact'
    weight: 50
  - name : Curriculum Vitae
    url : '/post/cv/'
    weight : 60
  - name : Projects
    url : ''
    weight : 70
  - name : Paleomagnetism.org
    url : /post/paleomagnetism/
    weight : 71
    parent: Projects
  - name : X-BADZUPA
    url : /post/xbadzupa/
    weight : 71
    parent: Projects
  - name : Music
    url : /post/music/
    weight : 73
    parent: Projects

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
